// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.7.1
// source: ClientTransferDataProtoc.proto

package common

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ClientTransferDataProtoc struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Info string `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ClientTransferDataProtoc) Reset() {
	*x = ClientTransferDataProtoc{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ClientTransferDataProtoc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientTransferDataProtoc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTransferDataProtoc) ProtoMessage() {}

func (x *ClientTransferDataProtoc) ProtoReflect() protoreflect.Message {
	mi := &file_ClientTransferDataProtoc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTransferDataProtoc.ProtoReflect.Descriptor instead.
func (*ClientTransferDataProtoc) Descriptor() ([]byte, []int) {
	return file_ClientTransferDataProtoc_proto_rawDescGZIP(), []int{0}
}

func (x *ClientTransferDataProtoc) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ClientTransferDataProtoc) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ClientTransferDataProtoc) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_ClientTransferDataProtoc_proto protoreflect.FileDescriptor

var file_ClientTransferDataProtoc_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x56, 0x0a, 0x18, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66,
	0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ClientTransferDataProtoc_proto_rawDescOnce sync.Once
	file_ClientTransferDataProtoc_proto_rawDescData = file_ClientTransferDataProtoc_proto_rawDesc
)

func file_ClientTransferDataProtoc_proto_rawDescGZIP() []byte {
	file_ClientTransferDataProtoc_proto_rawDescOnce.Do(func() {
		file_ClientTransferDataProtoc_proto_rawDescData = protoimpl.X.CompressGZIP(file_ClientTransferDataProtoc_proto_rawDescData)
	})
	return file_ClientTransferDataProtoc_proto_rawDescData
}

var file_ClientTransferDataProtoc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ClientTransferDataProtoc_proto_goTypes = []interface{}{
	(*ClientTransferDataProtoc)(nil), // 0: ClientTransferDataProtoc
}
var file_ClientTransferDataProtoc_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ClientTransferDataProtoc_proto_init() }
func file_ClientTransferDataProtoc_proto_init() {
	if File_ClientTransferDataProtoc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ClientTransferDataProtoc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientTransferDataProtoc); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ClientTransferDataProtoc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ClientTransferDataProtoc_proto_goTypes,
		DependencyIndexes: file_ClientTransferDataProtoc_proto_depIdxs,
		MessageInfos:      file_ClientTransferDataProtoc_proto_msgTypes,
	}.Build()
	File_ClientTransferDataProtoc_proto = out.File
	file_ClientTransferDataProtoc_proto_rawDesc = nil
	file_ClientTransferDataProtoc_proto_goTypes = nil
	file_ClientTransferDataProtoc_proto_depIdxs = nil
}
